### ISSUE TITLE
Incorrectly parsing input quasi UTC

### ISSUE THREAD

**Issue by sshaikh** [TotallyInformation/node-red-contrib-moment#24]
I have been passed a string:

`2019-05-25T15:30:42.526058+00:00`

When passing this wholesale through the moment node I get this output:

`2019-02-27T15:30:42.526Z`

If I manipulate the string:

str.substring(0,23) + "Z"

That fixes it. 

I'm posting the issue here primarily because I'm not sure how the moment node passes the string to the moment library, so am not sure where the bug is (if its a bug at all - the input timestamp does look legitimate enough).

**Comment by TotallyInformation** [comment]
Hi, thanks for this. I need to test against MomentJS itself to see if this is an upstream bug or not.

A quick test shows that it is the 6th decimal place on the seconds value that causes the issue. Reduced to 5 is no problem. Will now test with raw moment.

**Comment by TotallyInformation** [comment]
OK, got it. It is an upstream bug in moment-parseformat.

I use that so as to give the widest possible chance at parsing inputs in different formats.

But it produces weird outputs beyond 3dp:

```
fmt6dp parseFormat YYYY-MM-DDTHH:mm:ss.SSSDDDZ
fmt5dp parseFormat YYYY-MM-DDTHH:mm:ss.SSSDDZ
```

Reported upstream:

https://github.com/gr2m/moment-parseformat/issues/96

But I'm not hopeful of a resolution since there are many other outstanding issues back to 2016.

**Comment by sshaikh** [comment]
Thanks for the investigation and the follow up!

**Comment by TotallyInformation** [comment]
Clearly the upstream author is not willing to fix this issue so I will add a work-around to limit the number of decimal places.

Added to backlog and a fix will be provided in an upcoming release.

**Comment by TotallyInformation** [comment]
Workaround added to next release.
