### ISSUE TITLE
Timezone Problem

### ISSUE THREAD

**Issue by rickrina** [TotallyInformation/node-red-contrib-moment#26]
Hello,

i have problems getting a timestamp in the correct timezone.
If i set it to use UTC it puts out 1 p.m. (UTC is at 3p.m. at the moment)

If i put in anything in the local field it puts out the UTC time (3p.m.).

Is there any way to get the correct time? at the moment that should be 5p.m.

I tried "de" an many other things in the local field.

**Comment by TotallyInformation** [comment]
Please can you show your settings, input data and output data. Also it is helpful to know whether you have the latest version installed and what version of Node.js and Node-RED you are running. Finally, it is useful to know what OS and version you are running.

**Comment by Just-another-pleb** [comment]
Hi.
Not sure if this is related, but I think it could be.

I am having a lot of trouble with getting the correct output for DD-MM and MM-DD.

Here is a flow which shows clearly the problem:

```
[{"id":"35804bcb.cfa3b4","type":"function","z":"a941e919.4a7d88","name":"Time Stamp","func":"var d = new Date().toLocaleString();\nmsg.payload = d;\nreturn msg;","outputs":1,"noerr":0,"x":420,"y":360,"wires":[["a14fc634.236a58","1e45ce85.75bc79","861d21df.d065e","588b1172.c585f"]]},{"id":"a14fc634.236a58","type":"moment","z":"a941e919.4a7d88","name":"MM-DD","topic":"","input":"payload","inputType":"msg","inTz":"Australia/Sydney","adjAmount":0,"adjType":"days","adjDir":"add","format":"YYYY-MM-DD HH:mm:ss","locale":"en_AU","output":"payload","outputType":"msg","outTz":"Australia/Sydney","x":570,"y":360,"wires":[["b475d6b2.e14ce"]]},{"id":"1e45ce85.75bc79","type":"moment","z":"a941e919.4a7d88","name":"DD-MM","topic":"","input":"payload","inputType":"msg","inTz":"Australia/Sydney","adjAmount":0,"adjType":"days","adjDir":"add","format":"YYYY-DD-MM HH:mm:ss","locale":"en_AU","output":"payload","outputType":"msg","outTz":"Australia/Sydney","x":570,"y":400,"wires":[["3e04c264.1fa166"]]},{"id":"861d21df.d065e","type":"debug","z":"a941e919.4a7d88","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":580,"y":320,"wires":[]},{"id":"588b1172.c585f","type":"moment","z":"a941e919.4a7d88","name":"EU/UK","topic":"","input":"payload","inputType":"msg","inTz":"Australia/Sydney","adjAmount":0,"adjType":"days","adjDir":"add","format":"YYYY-MM-DD HH:mm:ss","locale":"EU/UK","output":"payload","outputType":"msg","outTz":"Australia/Sydney","x":560,"y":450,"wires":[["fac72b73.0c89f"]]},{"id":"981247e6.8d8b","type":"inject","z":"a941e919.4a7d88","name":"","topic":"","payload":"foo","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":260,"y":360,"wires":[["35804bcb.cfa3b4"]]},{"id":"b475d6b2.e14ce","type":"debug","z":"a941e919.4a7d88","name":"MM-DD","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":750,"y":360,"wires":[]},{"id":"3e04c264.1fa166","type":"debug","z":"a941e919.4a7d88","name":"DD-MM","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":750,"y":400,"wires":[]},{"id":"fac72b73.0c89f","type":"debug","z":"a941e919.4a7d88","name":"EU/UK","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":740,"y":450,"wires":[]}]
```

Screen shot:
Note local time at top.
09:38


![Screenshot from 2020-03-07 09-38-04](https://user-images.githubusercontent.com/39888280/76129424-83ef2600-605b-11ea-869f-8bc8ec984508.png)



The `moment` nodes are set to display the date as shown in their names.
The first two have it set as en_AU.

I have tried with a `moment` node and its local to EU/UK but it doesn't help.
With it displaying YYYY-MM-DD I still get YYYY-DD-MM.

Checking local settings for timezone - they are good.

```
me@me-desktop:~$ sudo dpkg-reconfigure tzdata
[sudo] password for me: 

Current default time zone: 'Australia/Sydney'
Local time is now:      Sat Mar  7 09:56:20 AEDT 2020.
Universal Time is now:  Fri Mar  6 22:56:20 UTC 2020.

me@me-desktop:~$
```

So I am not understanding why I have the node set to show MM-DD and get DD-MM from it.
Where as if I set it to DD-MM I get MM-DD.

This may be because of the *tricky* date being 07-03.  (7 March).
But as the timezone thingy is set, that should not be a problem.

I hope this helps the problem.

A couple of other things I have noticed:
How long it takes to send the second message.
20 seconds!

This may help find the problem.  Don't know.   But it could be getting stuck in parsing the input and reformatting it.

Just thinking aloud.

**Comment by TotallyInformation** [comment]
Not really sure that your second example relates to the first.

In order to understand your initial issue with timezones, I need example data and moment configurations that both work and don't work for you. Then I can trace the issue and either find a work-around or apply a fix to the node.

---
This 2nd issue appears to be the same as discussed here:

https://discourse.nodered.org/t/node-moment-output-format-calendar-different-results

Can you confirm?

For reference, that issue is a known one and referenced in the documentation. It is due to the difficulties of parsing input dates that are ambiguous (e.g. could be MM/DD or DD/MM). Without further information, it is impossible for the moment node to "know" which is correct so it assumes EU format.

Please use unambiguous date formats. I've published some recommendations about working with dates and timestamps on my blog.

https://it.knightnet.org.uk/blog/rules-for-working-with-dates-and-times/

**Comment by TotallyInformation** [comment]
Closed due to inactivity.
