### ISSUE TITLE
How to append time to payload?

### ISSUE THREAD

**Issue by 877dev** [TotallyInformation/node-red-contrib-moment#29]
I seem to be missing something obvious. I have a true or false switch node, when "false" is outputted I want to set the payload message to "<time/date> Door is open".

As the input to the moment node is to be triggered by a "false" message from the switch node, I can't see how to get the time/date appended.

Any ideas?

**Comment by 877dev** [comment]
Setting up like this I get the date passed through but not the time for some reason...

![image](https://user-images.githubusercontent.com/46575282/76162906-b96a4100-6139-11ea-9aab-238e152a6ff5.png)

**Comment by TotallyInformation** [comment]
Hi, thanks for raising. Often best to raise general questions in the Node-RED forum though as you tend to get a faster and possibly more complete response because lots of people will be looking at it.

In this case, if I've understood you correctly, you have two choices:

1. Use MomentJS's formatting. You can add text to the output format by escaping it with square brackets.

   See [here](https://momentjs.com/docs/#/displaying/format/) under "Escaping Characters" for details.

   `[today] dddd`

   ![image](https://user-images.githubusercontent.com/1591850/76216413-77f49700-6208-11ea-8b1c-42da4ffce310.png)


2. Alternatively, add the timestamp to some field other than payload and then use a change node after the moment node to merge the timestamp with whatever other text you want.

**Comment by 877dev** [comment]
Hi @TotallyInformation 

Thank you, although that is also useful I don't think I explained myself clearly.
The issue is that unless I use a timestamp trigger node, the time does not set and it shows 00:00. The date is correct. 

I've posted over on node red as you suggested [HERE](https://discourse.nodered.org/t/node-red-contrib-moment-how-to-add-timestamp-from-incoming-mqtt-node/22873)

Many thanks
877dev
