### ISSUE TITLE
How to get output showing more than the highest unit in humanizer

### ISSUE THREAD

**Issue by proffalken** [TotallyInformation/node-red-contrib-moment#30]
Hello,

I have a use-case where I would like to see the number of seconds displayed in a humanised format, however I'd like to see it broken down by more than just one unit.

As an example:

11,234 Seconds = 3.1205 Hours = 3 Hours, 7 Minutes and 14 Seconds

At the moment, all I get returned is `3 hours`, whereas I'd like to see the minutes and seconds as well.

Have I missed a setting somewhere?

**Comment by TotallyInformation** [comment]
Apologies, not sure why I didn't respond to this.

This is a _duration_ rather than a date/time value. MomentJS does have durations but they are not currently exposed in this node.

However, good news is that you can do this with a Change node and JSONata which now has moment built in giving you full access.

**Comment by proffalken** [comment]
Thanks!
