### ISSUE TITLE
Incorrect hour (midnight to 0100) local time

### ISSUE THREAD

**Issue by drmibell** [TotallyInformation/node-red-contrib-moment#7]
I am using node-red-contrib-moment 2.0.0 with node-red 0.14.5 and find that the hour between midnight and 0100 is reported as 24 instead of 00, when moment is configured as shown:

![moment](https://cloud.githubusercontent.com/assets/19335906/17759073/85df0252-64c2-11e6-8391-301dc226f69a.jpg)

**Comment by TotallyInformation** [comment]
Hi Michael, thanks for reporting this. However, I _think_ that may be the expected behaviour. Certainly that appears to be the [way that moment.js behaves](http://momentjs.com/docs/#/displaying/). If you want 00 instead of 24, you should use `HH` instead of `kk`.

Let me know if I'm wrong and I will dig further.

**Comment by drmibell** [comment]
Thanks. Clearly, you're right. I should have looked at the documentation instead of some tutorial that referred vaguely to "24-hr time." It never occurred to me that anyone would want to number the hours 1-24 instead of 0-23. Lesson learned.
